/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentencesRouteImport } from './routes/sentences'
import { Route as IndexRouteImport } from './routes/index'

const SentencesRoute = SentencesRouteImport.update({
  id: '/sentences',
  path: '/sentences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sentences': typeof SentencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sentences': typeof SentencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sentences': typeof SentencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sentences'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sentences'
  id: '__root__' | '/' | '/sentences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SentencesRoute: typeof SentencesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentences': {
      id: '/sentences'
      path: '/sentences'
      fullPath: '/sentences'
      preLoaderRoute: typeof SentencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SentencesRoute: SentencesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
