/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingPromptsRouteImport } from './routes/writing-prompts'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as VocabRouteImport } from './routes/vocab'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SentencesRouteImport } from './routes/sentences'
import { Route as RenshuuRouteImport } from './routes/renshuu'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AnkiRouteImport } from './routes/anki'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as ShadowingIndexRouteImport } from './routes/shadowing.index'
import { Route as QuestionSheetsIndexRouteImport } from './routes/question-sheets.index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as MyWritingIndexRouteImport } from './routes/my-writing.index'
import { Route as MySentencesIndexRouteImport } from './routes/my-sentences.index'
import { Route as ListeningSessionsIndexRouteImport } from './routes/listening-sessions.index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as CapturesIndexRouteImport } from './routes/captures.index'
import { Route as BookExercisesIndexRouteImport } from './routes/book-exercises.index'
import { Route as AnswerSheetsIndexRouteImport } from './routes/answer-sheets.index'
import { Route as WritingPromptsIdRouteImport } from './routes/writing-prompts.$id'
import { Route as SourcesIdRouteImport } from './routes/sources.$id'
import { Route as ShadowingNewRouteImport } from './routes/shadowing.new'
import { Route as ShadowingIdRouteImport } from './routes/shadowing.$id'
import { Route as QuestionSheetsNewRouteImport } from './routes/question-sheets.new'
import { Route as QuestionSheetsIdRouteImport } from './routes/question-sheets.$id'
import { Route as PracticeNewRouteImport } from './routes/practice.new'
import { Route as PracticeIdRouteImport } from './routes/practice.$id'
import { Route as MyWritingIdRouteImport } from './routes/my-writing.$id'
import { Route as MySentencesNewRouteImport } from './routes/my-sentences.new'
import { Route as MySentencesIdRouteImport } from './routes/my-sentences.$id'
import { Route as ListeningSessionsNewRouteImport } from './routes/listening-sessions.new'
import { Route as ListeningSessionsIdRouteImport } from './routes/listening-sessions.$id'
import { Route as LessonsNewRouteImport } from './routes/lessons.new'
import { Route as LessonsSlugRouteImport } from './routes/lessons.$slug'
import { Route as CapturesIdRouteImport } from './routes/captures.$id'
import { Route as AnswerSheetsNewRouteImport } from './routes/answer-sheets.new'
import { Route as AnswerSheetsIdRouteImport } from './routes/answer-sheets.$id'
import { Route as ShadowingIdIndexRouteImport } from './routes/shadowing.$id.index'
import { Route as QuestionSheetsIdIndexRouteImport } from './routes/question-sheets.$id.index'
import { Route as PracticeIdIndexRouteImport } from './routes/practice.$id.index'
import { Route as MySentencesIdIndexRouteImport } from './routes/my-sentences.$id.index'
import { Route as ListeningSessionsIdIndexRouteImport } from './routes/listening-sessions.$id.index'
import { Route as AnswerSheetsIdIndexRouteImport } from './routes/answer-sheets.$id.index'
import { Route as ShadowingIdEditRouteImport } from './routes/shadowing.$id.edit'
import { Route as QuestionSheetsIdEditRouteImport } from './routes/question-sheets.$id.edit'
import { Route as PracticeIdEditRouteImport } from './routes/practice.$id.edit'
import { Route as MySentencesIdEditRouteImport } from './routes/my-sentences.$id.edit'
import { Route as ListeningSessionsIdEditRouteImport } from './routes/listening-sessions.$id.edit'
import { Route as AnswerSheetsIdEditRouteImport } from './routes/answer-sheets.$id.edit'

const WritingPromptsRoute = WritingPromptsRouteImport.update({
  id: '/writing-prompts',
  path: '/writing-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabRoute = VocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SentencesRoute = SentencesRouteImport.update({
  id: '/sentences',
  path: '/sentences',
  getParentRoute: () => rootRouteImport,
} as any)
const RenshuuRoute = RenshuuRouteImport.update({
  id: '/renshuu',
  path: '/renshuu',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AnkiRoute = AnkiRouteImport.update({
  id: '/anki',
  path: '/anki',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowingIndexRoute = ShadowingIndexRouteImport.update({
  id: '/shadowing/',
  path: '/shadowing/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionSheetsIndexRoute = QuestionSheetsIndexRouteImport.update({
  id: '/question-sheets/',
  path: '/question-sheets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWritingIndexRoute = MyWritingIndexRouteImport.update({
  id: '/my-writing/',
  path: '/my-writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const MySentencesIndexRoute = MySentencesIndexRouteImport.update({
  id: '/my-sentences/',
  path: '/my-sentences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningSessionsIndexRoute = ListeningSessionsIndexRouteImport.update({
  id: '/listening-sessions/',
  path: '/listening-sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesIndexRoute = CapturesIndexRouteImport.update({
  id: '/captures/',
  path: '/captures/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookExercisesIndexRoute = BookExercisesIndexRouteImport.update({
  id: '/book-exercises/',
  path: '/book-exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerSheetsIndexRoute = AnswerSheetsIndexRouteImport.update({
  id: '/answer-sheets/',
  path: '/answer-sheets/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingPromptsIdRoute = WritingPromptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WritingPromptsRoute,
} as any)
const SourcesIdRoute = SourcesIdRouteImport.update({
  id: '/sources/$id',
  path: '/sources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowingNewRoute = ShadowingNewRouteImport.update({
  id: '/shadowing/new',
  path: '/shadowing/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowingIdRoute = ShadowingIdRouteImport.update({
  id: '/shadowing/$id',
  path: '/shadowing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionSheetsNewRoute = QuestionSheetsNewRouteImport.update({
  id: '/question-sheets/new',
  path: '/question-sheets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionSheetsIdRoute = QuestionSheetsIdRouteImport.update({
  id: '/question-sheets/$id',
  path: '/question-sheets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeNewRoute = PracticeNewRouteImport.update({
  id: '/practice/new',
  path: '/practice/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIdRoute = PracticeIdRouteImport.update({
  id: '/practice/$id',
  path: '/practice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWritingIdRoute = MyWritingIdRouteImport.update({
  id: '/my-writing/$id',
  path: '/my-writing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MySentencesNewRoute = MySentencesNewRouteImport.update({
  id: '/my-sentences/new',
  path: '/my-sentences/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MySentencesIdRoute = MySentencesIdRouteImport.update({
  id: '/my-sentences/$id',
  path: '/my-sentences/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningSessionsNewRoute = ListeningSessionsNewRouteImport.update({
  id: '/listening-sessions/new',
  path: '/listening-sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningSessionsIdRoute = ListeningSessionsIdRouteImport.update({
  id: '/listening-sessions/$id',
  path: '/listening-sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsNewRoute = LessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsSlugRoute = LessonsSlugRouteImport.update({
  id: '/lessons/$slug',
  path: '/lessons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesIdRoute = CapturesIdRouteImport.update({
  id: '/captures/$id',
  path: '/captures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerSheetsNewRoute = AnswerSheetsNewRouteImport.update({
  id: '/answer-sheets/new',
  path: '/answer-sheets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerSheetsIdRoute = AnswerSheetsIdRouteImport.update({
  id: '/answer-sheets/$id',
  path: '/answer-sheets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowingIdIndexRoute = ShadowingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShadowingIdRoute,
} as any)
const QuestionSheetsIdIndexRoute = QuestionSheetsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestionSheetsIdRoute,
} as any)
const PracticeIdIndexRoute = PracticeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeIdRoute,
} as any)
const MySentencesIdIndexRoute = MySentencesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MySentencesIdRoute,
} as any)
const ListeningSessionsIdIndexRoute =
  ListeningSessionsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ListeningSessionsIdRoute,
  } as any)
const AnswerSheetsIdIndexRoute = AnswerSheetsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnswerSheetsIdRoute,
} as any)
const ShadowingIdEditRoute = ShadowingIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ShadowingIdRoute,
} as any)
const QuestionSheetsIdEditRoute = QuestionSheetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => QuestionSheetsIdRoute,
} as any)
const PracticeIdEditRoute = PracticeIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PracticeIdRoute,
} as any)
const MySentencesIdEditRoute = MySentencesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MySentencesIdRoute,
} as any)
const ListeningSessionsIdEditRoute = ListeningSessionsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ListeningSessionsIdRoute,
} as any)
const AnswerSheetsIdEditRoute = AnswerSheetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AnswerSheetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anki': typeof AnkiRoute
  '/capture': typeof CaptureRoute
  '/culture': typeof CultureRoute
  '/grammar': typeof GrammarRoute
  '/renshuu': typeof RenshuuRoute
  '/sentences': typeof SentencesRoute
  '/settings': typeof SettingsRoute
  '/vocab': typeof VocabRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing-prompts': typeof WritingPromptsRouteWithChildren
  '/answer-sheets/$id': typeof AnswerSheetsIdRouteWithChildren
  '/answer-sheets/new': typeof AnswerSheetsNewRoute
  '/captures/$id': typeof CapturesIdRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/lessons/new': typeof LessonsNewRoute
  '/listening-sessions/$id': typeof ListeningSessionsIdRouteWithChildren
  '/listening-sessions/new': typeof ListeningSessionsNewRoute
  '/my-sentences/$id': typeof MySentencesIdRouteWithChildren
  '/my-sentences/new': typeof MySentencesNewRoute
  '/my-writing/$id': typeof MyWritingIdRoute
  '/practice/$id': typeof PracticeIdRouteWithChildren
  '/practice/new': typeof PracticeNewRoute
  '/question-sheets/$id': typeof QuestionSheetsIdRouteWithChildren
  '/question-sheets/new': typeof QuestionSheetsNewRoute
  '/shadowing/$id': typeof ShadowingIdRouteWithChildren
  '/shadowing/new': typeof ShadowingNewRoute
  '/sources/$id': typeof SourcesIdRoute
  '/writing-prompts/$id': typeof WritingPromptsIdRoute
  '/answer-sheets/': typeof AnswerSheetsIndexRoute
  '/book-exercises/': typeof BookExercisesIndexRoute
  '/captures/': typeof CapturesIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/listening-sessions/': typeof ListeningSessionsIndexRoute
  '/my-sentences/': typeof MySentencesIndexRoute
  '/my-writing/': typeof MyWritingIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/question-sheets/': typeof QuestionSheetsIndexRoute
  '/shadowing/': typeof ShadowingIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/answer-sheets/$id/edit': typeof AnswerSheetsIdEditRoute
  '/listening-sessions/$id/edit': typeof ListeningSessionsIdEditRoute
  '/my-sentences/$id/edit': typeof MySentencesIdEditRoute
  '/practice/$id/edit': typeof PracticeIdEditRoute
  '/question-sheets/$id/edit': typeof QuestionSheetsIdEditRoute
  '/shadowing/$id/edit': typeof ShadowingIdEditRoute
  '/answer-sheets/$id/': typeof AnswerSheetsIdIndexRoute
  '/listening-sessions/$id/': typeof ListeningSessionsIdIndexRoute
  '/my-sentences/$id/': typeof MySentencesIdIndexRoute
  '/practice/$id/': typeof PracticeIdIndexRoute
  '/question-sheets/$id/': typeof QuestionSheetsIdIndexRoute
  '/shadowing/$id/': typeof ShadowingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anki': typeof AnkiRoute
  '/capture': typeof CaptureRoute
  '/culture': typeof CultureRoute
  '/grammar': typeof GrammarRoute
  '/renshuu': typeof RenshuuRoute
  '/sentences': typeof SentencesRoute
  '/settings': typeof SettingsRoute
  '/vocab': typeof VocabRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing-prompts': typeof WritingPromptsRouteWithChildren
  '/answer-sheets/new': typeof AnswerSheetsNewRoute
  '/captures/$id': typeof CapturesIdRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/lessons/new': typeof LessonsNewRoute
  '/listening-sessions/new': typeof ListeningSessionsNewRoute
  '/my-sentences/new': typeof MySentencesNewRoute
  '/my-writing/$id': typeof MyWritingIdRoute
  '/practice/new': typeof PracticeNewRoute
  '/question-sheets/new': typeof QuestionSheetsNewRoute
  '/shadowing/new': typeof ShadowingNewRoute
  '/sources/$id': typeof SourcesIdRoute
  '/writing-prompts/$id': typeof WritingPromptsIdRoute
  '/answer-sheets': typeof AnswerSheetsIndexRoute
  '/book-exercises': typeof BookExercisesIndexRoute
  '/captures': typeof CapturesIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/listening-sessions': typeof ListeningSessionsIndexRoute
  '/my-sentences': typeof MySentencesIndexRoute
  '/my-writing': typeof MyWritingIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/question-sheets': typeof QuestionSheetsIndexRoute
  '/shadowing': typeof ShadowingIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/answer-sheets/$id/edit': typeof AnswerSheetsIdEditRoute
  '/listening-sessions/$id/edit': typeof ListeningSessionsIdEditRoute
  '/my-sentences/$id/edit': typeof MySentencesIdEditRoute
  '/practice/$id/edit': typeof PracticeIdEditRoute
  '/question-sheets/$id/edit': typeof QuestionSheetsIdEditRoute
  '/shadowing/$id/edit': typeof ShadowingIdEditRoute
  '/answer-sheets/$id': typeof AnswerSheetsIdIndexRoute
  '/listening-sessions/$id': typeof ListeningSessionsIdIndexRoute
  '/my-sentences/$id': typeof MySentencesIdIndexRoute
  '/practice/$id': typeof PracticeIdIndexRoute
  '/question-sheets/$id': typeof QuestionSheetsIdIndexRoute
  '/shadowing/$id': typeof ShadowingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anki': typeof AnkiRoute
  '/capture': typeof CaptureRoute
  '/culture': typeof CultureRoute
  '/grammar': typeof GrammarRoute
  '/renshuu': typeof RenshuuRoute
  '/sentences': typeof SentencesRoute
  '/settings': typeof SettingsRoute
  '/vocab': typeof VocabRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing-prompts': typeof WritingPromptsRouteWithChildren
  '/answer-sheets/$id': typeof AnswerSheetsIdRouteWithChildren
  '/answer-sheets/new': typeof AnswerSheetsNewRoute
  '/captures/$id': typeof CapturesIdRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/lessons/new': typeof LessonsNewRoute
  '/listening-sessions/$id': typeof ListeningSessionsIdRouteWithChildren
  '/listening-sessions/new': typeof ListeningSessionsNewRoute
  '/my-sentences/$id': typeof MySentencesIdRouteWithChildren
  '/my-sentences/new': typeof MySentencesNewRoute
  '/my-writing/$id': typeof MyWritingIdRoute
  '/practice/$id': typeof PracticeIdRouteWithChildren
  '/practice/new': typeof PracticeNewRoute
  '/question-sheets/$id': typeof QuestionSheetsIdRouteWithChildren
  '/question-sheets/new': typeof QuestionSheetsNewRoute
  '/shadowing/$id': typeof ShadowingIdRouteWithChildren
  '/shadowing/new': typeof ShadowingNewRoute
  '/sources/$id': typeof SourcesIdRoute
  '/writing-prompts/$id': typeof WritingPromptsIdRoute
  '/answer-sheets/': typeof AnswerSheetsIndexRoute
  '/book-exercises/': typeof BookExercisesIndexRoute
  '/captures/': typeof CapturesIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/listening-sessions/': typeof ListeningSessionsIndexRoute
  '/my-sentences/': typeof MySentencesIndexRoute
  '/my-writing/': typeof MyWritingIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/question-sheets/': typeof QuestionSheetsIndexRoute
  '/shadowing/': typeof ShadowingIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/answer-sheets/$id/edit': typeof AnswerSheetsIdEditRoute
  '/listening-sessions/$id/edit': typeof ListeningSessionsIdEditRoute
  '/my-sentences/$id/edit': typeof MySentencesIdEditRoute
  '/practice/$id/edit': typeof PracticeIdEditRoute
  '/question-sheets/$id/edit': typeof QuestionSheetsIdEditRoute
  '/shadowing/$id/edit': typeof ShadowingIdEditRoute
  '/answer-sheets/$id/': typeof AnswerSheetsIdIndexRoute
  '/listening-sessions/$id/': typeof ListeningSessionsIdIndexRoute
  '/my-sentences/$id/': typeof MySentencesIdIndexRoute
  '/practice/$id/': typeof PracticeIdIndexRoute
  '/question-sheets/$id/': typeof QuestionSheetsIdIndexRoute
  '/shadowing/$id/': typeof ShadowingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anki'
    | '/capture'
    | '/culture'
    | '/grammar'
    | '/renshuu'
    | '/sentences'
    | '/settings'
    | '/vocab'
    | '/vocabulary'
    | '/writing-prompts'
    | '/answer-sheets/$id'
    | '/answer-sheets/new'
    | '/captures/$id'
    | '/lessons/$slug'
    | '/lessons/new'
    | '/listening-sessions/$id'
    | '/listening-sessions/new'
    | '/my-sentences/$id'
    | '/my-sentences/new'
    | '/my-writing/$id'
    | '/practice/$id'
    | '/practice/new'
    | '/question-sheets/$id'
    | '/question-sheets/new'
    | '/shadowing/$id'
    | '/shadowing/new'
    | '/sources/$id'
    | '/writing-prompts/$id'
    | '/answer-sheets/'
    | '/book-exercises/'
    | '/captures/'
    | '/lessons/'
    | '/listening-sessions/'
    | '/my-sentences/'
    | '/my-writing/'
    | '/practice/'
    | '/question-sheets/'
    | '/shadowing/'
    | '/sources/'
    | '/answer-sheets/$id/edit'
    | '/listening-sessions/$id/edit'
    | '/my-sentences/$id/edit'
    | '/practice/$id/edit'
    | '/question-sheets/$id/edit'
    | '/shadowing/$id/edit'
    | '/answer-sheets/$id/'
    | '/listening-sessions/$id/'
    | '/my-sentences/$id/'
    | '/practice/$id/'
    | '/question-sheets/$id/'
    | '/shadowing/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anki'
    | '/capture'
    | '/culture'
    | '/grammar'
    | '/renshuu'
    | '/sentences'
    | '/settings'
    | '/vocab'
    | '/vocabulary'
    | '/writing-prompts'
    | '/answer-sheets/new'
    | '/captures/$id'
    | '/lessons/$slug'
    | '/lessons/new'
    | '/listening-sessions/new'
    | '/my-sentences/new'
    | '/my-writing/$id'
    | '/practice/new'
    | '/question-sheets/new'
    | '/shadowing/new'
    | '/sources/$id'
    | '/writing-prompts/$id'
    | '/answer-sheets'
    | '/book-exercises'
    | '/captures'
    | '/lessons'
    | '/listening-sessions'
    | '/my-sentences'
    | '/my-writing'
    | '/practice'
    | '/question-sheets'
    | '/shadowing'
    | '/sources'
    | '/answer-sheets/$id/edit'
    | '/listening-sessions/$id/edit'
    | '/my-sentences/$id/edit'
    | '/practice/$id/edit'
    | '/question-sheets/$id/edit'
    | '/shadowing/$id/edit'
    | '/answer-sheets/$id'
    | '/listening-sessions/$id'
    | '/my-sentences/$id'
    | '/practice/$id'
    | '/question-sheets/$id'
    | '/shadowing/$id'
  id:
    | '__root__'
    | '/'
    | '/anki'
    | '/capture'
    | '/culture'
    | '/grammar'
    | '/renshuu'
    | '/sentences'
    | '/settings'
    | '/vocab'
    | '/vocabulary'
    | '/writing-prompts'
    | '/answer-sheets/$id'
    | '/answer-sheets/new'
    | '/captures/$id'
    | '/lessons/$slug'
    | '/lessons/new'
    | '/listening-sessions/$id'
    | '/listening-sessions/new'
    | '/my-sentences/$id'
    | '/my-sentences/new'
    | '/my-writing/$id'
    | '/practice/$id'
    | '/practice/new'
    | '/question-sheets/$id'
    | '/question-sheets/new'
    | '/shadowing/$id'
    | '/shadowing/new'
    | '/sources/$id'
    | '/writing-prompts/$id'
    | '/answer-sheets/'
    | '/book-exercises/'
    | '/captures/'
    | '/lessons/'
    | '/listening-sessions/'
    | '/my-sentences/'
    | '/my-writing/'
    | '/practice/'
    | '/question-sheets/'
    | '/shadowing/'
    | '/sources/'
    | '/answer-sheets/$id/edit'
    | '/listening-sessions/$id/edit'
    | '/my-sentences/$id/edit'
    | '/practice/$id/edit'
    | '/question-sheets/$id/edit'
    | '/shadowing/$id/edit'
    | '/answer-sheets/$id/'
    | '/listening-sessions/$id/'
    | '/my-sentences/$id/'
    | '/practice/$id/'
    | '/question-sheets/$id/'
    | '/shadowing/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnkiRoute: typeof AnkiRoute
  CaptureRoute: typeof CaptureRoute
  CultureRoute: typeof CultureRoute
  GrammarRoute: typeof GrammarRoute
  RenshuuRoute: typeof RenshuuRoute
  SentencesRoute: typeof SentencesRoute
  SettingsRoute: typeof SettingsRoute
  VocabRoute: typeof VocabRoute
  VocabularyRoute: typeof VocabularyRoute
  WritingPromptsRoute: typeof WritingPromptsRouteWithChildren
  AnswerSheetsIdRoute: typeof AnswerSheetsIdRouteWithChildren
  AnswerSheetsNewRoute: typeof AnswerSheetsNewRoute
  CapturesIdRoute: typeof CapturesIdRoute
  LessonsSlugRoute: typeof LessonsSlugRoute
  LessonsNewRoute: typeof LessonsNewRoute
  ListeningSessionsIdRoute: typeof ListeningSessionsIdRouteWithChildren
  ListeningSessionsNewRoute: typeof ListeningSessionsNewRoute
  MySentencesIdRoute: typeof MySentencesIdRouteWithChildren
  MySentencesNewRoute: typeof MySentencesNewRoute
  MyWritingIdRoute: typeof MyWritingIdRoute
  PracticeIdRoute: typeof PracticeIdRouteWithChildren
  PracticeNewRoute: typeof PracticeNewRoute
  QuestionSheetsIdRoute: typeof QuestionSheetsIdRouteWithChildren
  QuestionSheetsNewRoute: typeof QuestionSheetsNewRoute
  ShadowingIdRoute: typeof ShadowingIdRouteWithChildren
  ShadowingNewRoute: typeof ShadowingNewRoute
  SourcesIdRoute: typeof SourcesIdRoute
  AnswerSheetsIndexRoute: typeof AnswerSheetsIndexRoute
  BookExercisesIndexRoute: typeof BookExercisesIndexRoute
  CapturesIndexRoute: typeof CapturesIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  ListeningSessionsIndexRoute: typeof ListeningSessionsIndexRoute
  MySentencesIndexRoute: typeof MySentencesIndexRoute
  MyWritingIndexRoute: typeof MyWritingIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  QuestionSheetsIndexRoute: typeof QuestionSheetsIndexRoute
  ShadowingIndexRoute: typeof ShadowingIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing-prompts': {
      id: '/writing-prompts'
      path: '/writing-prompts'
      fullPath: '/writing-prompts'
      preLoaderRoute: typeof WritingPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab': {
      id: '/vocab'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof VocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentences': {
      id: '/sentences'
      path: '/sentences'
      fullPath: '/sentences'
      preLoaderRoute: typeof SentencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renshuu': {
      id: '/renshuu'
      path: '/renshuu'
      fullPath: '/renshuu'
      preLoaderRoute: typeof RenshuuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anki': {
      id: '/anki'
      path: '/anki'
      fullPath: '/anki'
      preLoaderRoute: typeof AnkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadowing/': {
      id: '/shadowing/'
      path: '/shadowing'
      fullPath: '/shadowing/'
      preLoaderRoute: typeof ShadowingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-sheets/': {
      id: '/question-sheets/'
      path: '/question-sheets'
      fullPath: '/question-sheets/'
      preLoaderRoute: typeof QuestionSheetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-writing/': {
      id: '/my-writing/'
      path: '/my-writing'
      fullPath: '/my-writing/'
      preLoaderRoute: typeof MyWritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sentences/': {
      id: '/my-sentences/'
      path: '/my-sentences'
      fullPath: '/my-sentences/'
      preLoaderRoute: typeof MySentencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening-sessions/': {
      id: '/listening-sessions/'
      path: '/listening-sessions'
      fullPath: '/listening-sessions/'
      preLoaderRoute: typeof ListeningSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures/': {
      id: '/captures/'
      path: '/captures'
      fullPath: '/captures/'
      preLoaderRoute: typeof CapturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-exercises/': {
      id: '/book-exercises/'
      path: '/book-exercises'
      fullPath: '/book-exercises/'
      preLoaderRoute: typeof BookExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer-sheets/': {
      id: '/answer-sheets/'
      path: '/answer-sheets'
      fullPath: '/answer-sheets/'
      preLoaderRoute: typeof AnswerSheetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing-prompts/$id': {
      id: '/writing-prompts/$id'
      path: '/$id'
      fullPath: '/writing-prompts/$id'
      preLoaderRoute: typeof WritingPromptsIdRouteImport
      parentRoute: typeof WritingPromptsRoute
    }
    '/sources/$id': {
      id: '/sources/$id'
      path: '/sources/$id'
      fullPath: '/sources/$id'
      preLoaderRoute: typeof SourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadowing/new': {
      id: '/shadowing/new'
      path: '/shadowing/new'
      fullPath: '/shadowing/new'
      preLoaderRoute: typeof ShadowingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadowing/$id': {
      id: '/shadowing/$id'
      path: '/shadowing/$id'
      fullPath: '/shadowing/$id'
      preLoaderRoute: typeof ShadowingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-sheets/new': {
      id: '/question-sheets/new'
      path: '/question-sheets/new'
      fullPath: '/question-sheets/new'
      preLoaderRoute: typeof QuestionSheetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-sheets/$id': {
      id: '/question-sheets/$id'
      path: '/question-sheets/$id'
      fullPath: '/question-sheets/$id'
      preLoaderRoute: typeof QuestionSheetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/new': {
      id: '/practice/new'
      path: '/practice/new'
      fullPath: '/practice/new'
      preLoaderRoute: typeof PracticeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$id': {
      id: '/practice/$id'
      path: '/practice/$id'
      fullPath: '/practice/$id'
      preLoaderRoute: typeof PracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-writing/$id': {
      id: '/my-writing/$id'
      path: '/my-writing/$id'
      fullPath: '/my-writing/$id'
      preLoaderRoute: typeof MyWritingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sentences/new': {
      id: '/my-sentences/new'
      path: '/my-sentences/new'
      fullPath: '/my-sentences/new'
      preLoaderRoute: typeof MySentencesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sentences/$id': {
      id: '/my-sentences/$id'
      path: '/my-sentences/$id'
      fullPath: '/my-sentences/$id'
      preLoaderRoute: typeof MySentencesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening-sessions/new': {
      id: '/listening-sessions/new'
      path: '/listening-sessions/new'
      fullPath: '/listening-sessions/new'
      preLoaderRoute: typeof ListeningSessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening-sessions/$id': {
      id: '/listening-sessions/$id'
      path: '/listening-sessions/$id'
      fullPath: '/listening-sessions/$id'
      preLoaderRoute: typeof ListeningSessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/new': {
      id: '/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof LessonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$slug': {
      id: '/lessons/$slug'
      path: '/lessons/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof LessonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures/$id': {
      id: '/captures/$id'
      path: '/captures/$id'
      fullPath: '/captures/$id'
      preLoaderRoute: typeof CapturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer-sheets/new': {
      id: '/answer-sheets/new'
      path: '/answer-sheets/new'
      fullPath: '/answer-sheets/new'
      preLoaderRoute: typeof AnswerSheetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer-sheets/$id': {
      id: '/answer-sheets/$id'
      path: '/answer-sheets/$id'
      fullPath: '/answer-sheets/$id'
      preLoaderRoute: typeof AnswerSheetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadowing/$id/': {
      id: '/shadowing/$id/'
      path: '/'
      fullPath: '/shadowing/$id/'
      preLoaderRoute: typeof ShadowingIdIndexRouteImport
      parentRoute: typeof ShadowingIdRoute
    }
    '/question-sheets/$id/': {
      id: '/question-sheets/$id/'
      path: '/'
      fullPath: '/question-sheets/$id/'
      preLoaderRoute: typeof QuestionSheetsIdIndexRouteImport
      parentRoute: typeof QuestionSheetsIdRoute
    }
    '/practice/$id/': {
      id: '/practice/$id/'
      path: '/'
      fullPath: '/practice/$id/'
      preLoaderRoute: typeof PracticeIdIndexRouteImport
      parentRoute: typeof PracticeIdRoute
    }
    '/my-sentences/$id/': {
      id: '/my-sentences/$id/'
      path: '/'
      fullPath: '/my-sentences/$id/'
      preLoaderRoute: typeof MySentencesIdIndexRouteImport
      parentRoute: typeof MySentencesIdRoute
    }
    '/listening-sessions/$id/': {
      id: '/listening-sessions/$id/'
      path: '/'
      fullPath: '/listening-sessions/$id/'
      preLoaderRoute: typeof ListeningSessionsIdIndexRouteImport
      parentRoute: typeof ListeningSessionsIdRoute
    }
    '/answer-sheets/$id/': {
      id: '/answer-sheets/$id/'
      path: '/'
      fullPath: '/answer-sheets/$id/'
      preLoaderRoute: typeof AnswerSheetsIdIndexRouteImport
      parentRoute: typeof AnswerSheetsIdRoute
    }
    '/shadowing/$id/edit': {
      id: '/shadowing/$id/edit'
      path: '/edit'
      fullPath: '/shadowing/$id/edit'
      preLoaderRoute: typeof ShadowingIdEditRouteImport
      parentRoute: typeof ShadowingIdRoute
    }
    '/question-sheets/$id/edit': {
      id: '/question-sheets/$id/edit'
      path: '/edit'
      fullPath: '/question-sheets/$id/edit'
      preLoaderRoute: typeof QuestionSheetsIdEditRouteImport
      parentRoute: typeof QuestionSheetsIdRoute
    }
    '/practice/$id/edit': {
      id: '/practice/$id/edit'
      path: '/edit'
      fullPath: '/practice/$id/edit'
      preLoaderRoute: typeof PracticeIdEditRouteImport
      parentRoute: typeof PracticeIdRoute
    }
    '/my-sentences/$id/edit': {
      id: '/my-sentences/$id/edit'
      path: '/edit'
      fullPath: '/my-sentences/$id/edit'
      preLoaderRoute: typeof MySentencesIdEditRouteImport
      parentRoute: typeof MySentencesIdRoute
    }
    '/listening-sessions/$id/edit': {
      id: '/listening-sessions/$id/edit'
      path: '/edit'
      fullPath: '/listening-sessions/$id/edit'
      preLoaderRoute: typeof ListeningSessionsIdEditRouteImport
      parentRoute: typeof ListeningSessionsIdRoute
    }
    '/answer-sheets/$id/edit': {
      id: '/answer-sheets/$id/edit'
      path: '/edit'
      fullPath: '/answer-sheets/$id/edit'
      preLoaderRoute: typeof AnswerSheetsIdEditRouteImport
      parentRoute: typeof AnswerSheetsIdRoute
    }
  }
}

interface WritingPromptsRouteChildren {
  WritingPromptsIdRoute: typeof WritingPromptsIdRoute
}

const WritingPromptsRouteChildren: WritingPromptsRouteChildren = {
  WritingPromptsIdRoute: WritingPromptsIdRoute,
}

const WritingPromptsRouteWithChildren = WritingPromptsRoute._addFileChildren(
  WritingPromptsRouteChildren,
)

interface AnswerSheetsIdRouteChildren {
  AnswerSheetsIdEditRoute: typeof AnswerSheetsIdEditRoute
  AnswerSheetsIdIndexRoute: typeof AnswerSheetsIdIndexRoute
}

const AnswerSheetsIdRouteChildren: AnswerSheetsIdRouteChildren = {
  AnswerSheetsIdEditRoute: AnswerSheetsIdEditRoute,
  AnswerSheetsIdIndexRoute: AnswerSheetsIdIndexRoute,
}

const AnswerSheetsIdRouteWithChildren = AnswerSheetsIdRoute._addFileChildren(
  AnswerSheetsIdRouteChildren,
)

interface ListeningSessionsIdRouteChildren {
  ListeningSessionsIdEditRoute: typeof ListeningSessionsIdEditRoute
  ListeningSessionsIdIndexRoute: typeof ListeningSessionsIdIndexRoute
}

const ListeningSessionsIdRouteChildren: ListeningSessionsIdRouteChildren = {
  ListeningSessionsIdEditRoute: ListeningSessionsIdEditRoute,
  ListeningSessionsIdIndexRoute: ListeningSessionsIdIndexRoute,
}

const ListeningSessionsIdRouteWithChildren =
  ListeningSessionsIdRoute._addFileChildren(ListeningSessionsIdRouteChildren)

interface MySentencesIdRouteChildren {
  MySentencesIdEditRoute: typeof MySentencesIdEditRoute
  MySentencesIdIndexRoute: typeof MySentencesIdIndexRoute
}

const MySentencesIdRouteChildren: MySentencesIdRouteChildren = {
  MySentencesIdEditRoute: MySentencesIdEditRoute,
  MySentencesIdIndexRoute: MySentencesIdIndexRoute,
}

const MySentencesIdRouteWithChildren = MySentencesIdRoute._addFileChildren(
  MySentencesIdRouteChildren,
)

interface PracticeIdRouteChildren {
  PracticeIdEditRoute: typeof PracticeIdEditRoute
  PracticeIdIndexRoute: typeof PracticeIdIndexRoute
}

const PracticeIdRouteChildren: PracticeIdRouteChildren = {
  PracticeIdEditRoute: PracticeIdEditRoute,
  PracticeIdIndexRoute: PracticeIdIndexRoute,
}

const PracticeIdRouteWithChildren = PracticeIdRoute._addFileChildren(
  PracticeIdRouteChildren,
)

interface QuestionSheetsIdRouteChildren {
  QuestionSheetsIdEditRoute: typeof QuestionSheetsIdEditRoute
  QuestionSheetsIdIndexRoute: typeof QuestionSheetsIdIndexRoute
}

const QuestionSheetsIdRouteChildren: QuestionSheetsIdRouteChildren = {
  QuestionSheetsIdEditRoute: QuestionSheetsIdEditRoute,
  QuestionSheetsIdIndexRoute: QuestionSheetsIdIndexRoute,
}

const QuestionSheetsIdRouteWithChildren =
  QuestionSheetsIdRoute._addFileChildren(QuestionSheetsIdRouteChildren)

interface ShadowingIdRouteChildren {
  ShadowingIdEditRoute: typeof ShadowingIdEditRoute
  ShadowingIdIndexRoute: typeof ShadowingIdIndexRoute
}

const ShadowingIdRouteChildren: ShadowingIdRouteChildren = {
  ShadowingIdEditRoute: ShadowingIdEditRoute,
  ShadowingIdIndexRoute: ShadowingIdIndexRoute,
}

const ShadowingIdRouteWithChildren = ShadowingIdRoute._addFileChildren(
  ShadowingIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnkiRoute: AnkiRoute,
  CaptureRoute: CaptureRoute,
  CultureRoute: CultureRoute,
  GrammarRoute: GrammarRoute,
  RenshuuRoute: RenshuuRoute,
  SentencesRoute: SentencesRoute,
  SettingsRoute: SettingsRoute,
  VocabRoute: VocabRoute,
  VocabularyRoute: VocabularyRoute,
  WritingPromptsRoute: WritingPromptsRouteWithChildren,
  AnswerSheetsIdRoute: AnswerSheetsIdRouteWithChildren,
  AnswerSheetsNewRoute: AnswerSheetsNewRoute,
  CapturesIdRoute: CapturesIdRoute,
  LessonsSlugRoute: LessonsSlugRoute,
  LessonsNewRoute: LessonsNewRoute,
  ListeningSessionsIdRoute: ListeningSessionsIdRouteWithChildren,
  ListeningSessionsNewRoute: ListeningSessionsNewRoute,
  MySentencesIdRoute: MySentencesIdRouteWithChildren,
  MySentencesNewRoute: MySentencesNewRoute,
  MyWritingIdRoute: MyWritingIdRoute,
  PracticeIdRoute: PracticeIdRouteWithChildren,
  PracticeNewRoute: PracticeNewRoute,
  QuestionSheetsIdRoute: QuestionSheetsIdRouteWithChildren,
  QuestionSheetsNewRoute: QuestionSheetsNewRoute,
  ShadowingIdRoute: ShadowingIdRouteWithChildren,
  ShadowingNewRoute: ShadowingNewRoute,
  SourcesIdRoute: SourcesIdRoute,
  AnswerSheetsIndexRoute: AnswerSheetsIndexRoute,
  BookExercisesIndexRoute: BookExercisesIndexRoute,
  CapturesIndexRoute: CapturesIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  ListeningSessionsIndexRoute: ListeningSessionsIndexRoute,
  MySentencesIndexRoute: MySentencesIndexRoute,
  MyWritingIndexRoute: MyWritingIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  QuestionSheetsIndexRoute: QuestionSheetsIndexRoute,
  ShadowingIndexRoute: ShadowingIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
