/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as VocabRouteImport } from './routes/vocab'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SentencesRouteImport } from './routes/sentences'
import { Route as RenshuuRouteImport } from './routes/renshuu'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AnkiRouteImport } from './routes/anki'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as MySentencesIndexRouteImport } from './routes/my-sentences.index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as CapturesIndexRouteImport } from './routes/captures.index'
import { Route as SourcesIdRouteImport } from './routes/sources.$id'
import { Route as PracticeNewRouteImport } from './routes/practice.new'
import { Route as PracticeIdRouteImport } from './routes/practice.$id'
import { Route as MySentencesNewRouteImport } from './routes/my-sentences.new'
import { Route as MySentencesIdRouteImport } from './routes/my-sentences.$id'
import { Route as LessonsNewRouteImport } from './routes/lessons.new'
import { Route as LessonsSlugRouteImport } from './routes/lessons.$slug'
import { Route as CapturesIdRouteImport } from './routes/captures.$id'
import { Route as PracticeIdIndexRouteImport } from './routes/practice.$id.index'
import { Route as MySentencesIdIndexRouteImport } from './routes/my-sentences.$id.index'
import { Route as PracticeIdEditRouteImport } from './routes/practice.$id.edit'
import { Route as MySentencesIdEditRouteImport } from './routes/my-sentences.$id.edit'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabRoute = VocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SentencesRoute = SentencesRouteImport.update({
  id: '/sentences',
  path: '/sentences',
  getParentRoute: () => rootRouteImport,
} as any)
const RenshuuRoute = RenshuuRouteImport.update({
  id: '/renshuu',
  path: '/renshuu',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AnkiRoute = AnkiRouteImport.update({
  id: '/anki',
  path: '/anki',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const MySentencesIndexRoute = MySentencesIndexRouteImport.update({
  id: '/my-sentences/',
  path: '/my-sentences/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesIndexRoute = CapturesIndexRouteImport.update({
  id: '/captures/',
  path: '/captures/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIdRoute = SourcesIdRouteImport.update({
  id: '/sources/$id',
  path: '/sources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeNewRoute = PracticeNewRouteImport.update({
  id: '/practice/new',
  path: '/practice/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIdRoute = PracticeIdRouteImport.update({
  id: '/practice/$id',
  path: '/practice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MySentencesNewRoute = MySentencesNewRouteImport.update({
  id: '/my-sentences/new',
  path: '/my-sentences/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MySentencesIdRoute = MySentencesIdRouteImport.update({
  id: '/my-sentences/$id',
  path: '/my-sentences/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsNewRoute = LessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsSlugRoute = LessonsSlugRouteImport.update({
  id: '/lessons/$slug',
  path: '/lessons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesIdRoute = CapturesIdRouteImport.update({
  id: '/captures/$id',
  path: '/captures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIdIndexRoute = PracticeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeIdRoute,
} as any)
const MySentencesIdIndexRoute = MySentencesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MySentencesIdRoute,
} as any)
const PracticeIdEditRoute = PracticeIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PracticeIdRoute,
} as any)
const MySentencesIdEditRoute = MySentencesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MySentencesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anki': typeof AnkiRoute
  '/capture': typeof CaptureRoute
  '/culture': typeof CultureRoute
  '/grammar': typeof GrammarRoute
  '/renshuu': typeof RenshuuRoute
  '/sentences': typeof SentencesRoute
  '/settings': typeof SettingsRoute
  '/vocab': typeof VocabRoute
  '/vocabulary': typeof VocabularyRoute
  '/captures/$id': typeof CapturesIdRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/lessons/new': typeof LessonsNewRoute
  '/my-sentences/$id': typeof MySentencesIdRouteWithChildren
  '/my-sentences/new': typeof MySentencesNewRoute
  '/practice/$id': typeof PracticeIdRouteWithChildren
  '/practice/new': typeof PracticeNewRoute
  '/sources/$id': typeof SourcesIdRoute
  '/captures/': typeof CapturesIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/my-sentences/': typeof MySentencesIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/my-sentences/$id/edit': typeof MySentencesIdEditRoute
  '/practice/$id/edit': typeof PracticeIdEditRoute
  '/my-sentences/$id/': typeof MySentencesIdIndexRoute
  '/practice/$id/': typeof PracticeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anki': typeof AnkiRoute
  '/capture': typeof CaptureRoute
  '/culture': typeof CultureRoute
  '/grammar': typeof GrammarRoute
  '/renshuu': typeof RenshuuRoute
  '/sentences': typeof SentencesRoute
  '/settings': typeof SettingsRoute
  '/vocab': typeof VocabRoute
  '/vocabulary': typeof VocabularyRoute
  '/captures/$id': typeof CapturesIdRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/lessons/new': typeof LessonsNewRoute
  '/my-sentences/new': typeof MySentencesNewRoute
  '/practice/new': typeof PracticeNewRoute
  '/sources/$id': typeof SourcesIdRoute
  '/captures': typeof CapturesIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/my-sentences': typeof MySentencesIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/my-sentences/$id/edit': typeof MySentencesIdEditRoute
  '/practice/$id/edit': typeof PracticeIdEditRoute
  '/my-sentences/$id': typeof MySentencesIdIndexRoute
  '/practice/$id': typeof PracticeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anki': typeof AnkiRoute
  '/capture': typeof CaptureRoute
  '/culture': typeof CultureRoute
  '/grammar': typeof GrammarRoute
  '/renshuu': typeof RenshuuRoute
  '/sentences': typeof SentencesRoute
  '/settings': typeof SettingsRoute
  '/vocab': typeof VocabRoute
  '/vocabulary': typeof VocabularyRoute
  '/captures/$id': typeof CapturesIdRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/lessons/new': typeof LessonsNewRoute
  '/my-sentences/$id': typeof MySentencesIdRouteWithChildren
  '/my-sentences/new': typeof MySentencesNewRoute
  '/practice/$id': typeof PracticeIdRouteWithChildren
  '/practice/new': typeof PracticeNewRoute
  '/sources/$id': typeof SourcesIdRoute
  '/captures/': typeof CapturesIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/my-sentences/': typeof MySentencesIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/my-sentences/$id/edit': typeof MySentencesIdEditRoute
  '/practice/$id/edit': typeof PracticeIdEditRoute
  '/my-sentences/$id/': typeof MySentencesIdIndexRoute
  '/practice/$id/': typeof PracticeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anki'
    | '/capture'
    | '/culture'
    | '/grammar'
    | '/renshuu'
    | '/sentences'
    | '/settings'
    | '/vocab'
    | '/vocabulary'
    | '/captures/$id'
    | '/lessons/$slug'
    | '/lessons/new'
    | '/my-sentences/$id'
    | '/my-sentences/new'
    | '/practice/$id'
    | '/practice/new'
    | '/sources/$id'
    | '/captures/'
    | '/lessons/'
    | '/my-sentences/'
    | '/practice/'
    | '/sources/'
    | '/my-sentences/$id/edit'
    | '/practice/$id/edit'
    | '/my-sentences/$id/'
    | '/practice/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anki'
    | '/capture'
    | '/culture'
    | '/grammar'
    | '/renshuu'
    | '/sentences'
    | '/settings'
    | '/vocab'
    | '/vocabulary'
    | '/captures/$id'
    | '/lessons/$slug'
    | '/lessons/new'
    | '/my-sentences/new'
    | '/practice/new'
    | '/sources/$id'
    | '/captures'
    | '/lessons'
    | '/my-sentences'
    | '/practice'
    | '/sources'
    | '/my-sentences/$id/edit'
    | '/practice/$id/edit'
    | '/my-sentences/$id'
    | '/practice/$id'
  id:
    | '__root__'
    | '/'
    | '/anki'
    | '/capture'
    | '/culture'
    | '/grammar'
    | '/renshuu'
    | '/sentences'
    | '/settings'
    | '/vocab'
    | '/vocabulary'
    | '/captures/$id'
    | '/lessons/$slug'
    | '/lessons/new'
    | '/my-sentences/$id'
    | '/my-sentences/new'
    | '/practice/$id'
    | '/practice/new'
    | '/sources/$id'
    | '/captures/'
    | '/lessons/'
    | '/my-sentences/'
    | '/practice/'
    | '/sources/'
    | '/my-sentences/$id/edit'
    | '/practice/$id/edit'
    | '/my-sentences/$id/'
    | '/practice/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnkiRoute: typeof AnkiRoute
  CaptureRoute: typeof CaptureRoute
  CultureRoute: typeof CultureRoute
  GrammarRoute: typeof GrammarRoute
  RenshuuRoute: typeof RenshuuRoute
  SentencesRoute: typeof SentencesRoute
  SettingsRoute: typeof SettingsRoute
  VocabRoute: typeof VocabRoute
  VocabularyRoute: typeof VocabularyRoute
  CapturesIdRoute: typeof CapturesIdRoute
  LessonsSlugRoute: typeof LessonsSlugRoute
  LessonsNewRoute: typeof LessonsNewRoute
  MySentencesIdRoute: typeof MySentencesIdRouteWithChildren
  MySentencesNewRoute: typeof MySentencesNewRoute
  PracticeIdRoute: typeof PracticeIdRouteWithChildren
  PracticeNewRoute: typeof PracticeNewRoute
  SourcesIdRoute: typeof SourcesIdRoute
  CapturesIndexRoute: typeof CapturesIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  MySentencesIndexRoute: typeof MySentencesIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab': {
      id: '/vocab'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof VocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentences': {
      id: '/sentences'
      path: '/sentences'
      fullPath: '/sentences'
      preLoaderRoute: typeof SentencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renshuu': {
      id: '/renshuu'
      path: '/renshuu'
      fullPath: '/renshuu'
      preLoaderRoute: typeof RenshuuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anki': {
      id: '/anki'
      path: '/anki'
      fullPath: '/anki'
      preLoaderRoute: typeof AnkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sentences/': {
      id: '/my-sentences/'
      path: '/my-sentences'
      fullPath: '/my-sentences/'
      preLoaderRoute: typeof MySentencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures/': {
      id: '/captures/'
      path: '/captures'
      fullPath: '/captures/'
      preLoaderRoute: typeof CapturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$id': {
      id: '/sources/$id'
      path: '/sources/$id'
      fullPath: '/sources/$id'
      preLoaderRoute: typeof SourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/new': {
      id: '/practice/new'
      path: '/practice/new'
      fullPath: '/practice/new'
      preLoaderRoute: typeof PracticeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$id': {
      id: '/practice/$id'
      path: '/practice/$id'
      fullPath: '/practice/$id'
      preLoaderRoute: typeof PracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sentences/new': {
      id: '/my-sentences/new'
      path: '/my-sentences/new'
      fullPath: '/my-sentences/new'
      preLoaderRoute: typeof MySentencesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sentences/$id': {
      id: '/my-sentences/$id'
      path: '/my-sentences/$id'
      fullPath: '/my-sentences/$id'
      preLoaderRoute: typeof MySentencesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/new': {
      id: '/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof LessonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$slug': {
      id: '/lessons/$slug'
      path: '/lessons/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof LessonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures/$id': {
      id: '/captures/$id'
      path: '/captures/$id'
      fullPath: '/captures/$id'
      preLoaderRoute: typeof CapturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$id/': {
      id: '/practice/$id/'
      path: '/'
      fullPath: '/practice/$id/'
      preLoaderRoute: typeof PracticeIdIndexRouteImport
      parentRoute: typeof PracticeIdRoute
    }
    '/my-sentences/$id/': {
      id: '/my-sentences/$id/'
      path: '/'
      fullPath: '/my-sentences/$id/'
      preLoaderRoute: typeof MySentencesIdIndexRouteImport
      parentRoute: typeof MySentencesIdRoute
    }
    '/practice/$id/edit': {
      id: '/practice/$id/edit'
      path: '/edit'
      fullPath: '/practice/$id/edit'
      preLoaderRoute: typeof PracticeIdEditRouteImport
      parentRoute: typeof PracticeIdRoute
    }
    '/my-sentences/$id/edit': {
      id: '/my-sentences/$id/edit'
      path: '/edit'
      fullPath: '/my-sentences/$id/edit'
      preLoaderRoute: typeof MySentencesIdEditRouteImport
      parentRoute: typeof MySentencesIdRoute
    }
  }
}

interface MySentencesIdRouteChildren {
  MySentencesIdEditRoute: typeof MySentencesIdEditRoute
  MySentencesIdIndexRoute: typeof MySentencesIdIndexRoute
}

const MySentencesIdRouteChildren: MySentencesIdRouteChildren = {
  MySentencesIdEditRoute: MySentencesIdEditRoute,
  MySentencesIdIndexRoute: MySentencesIdIndexRoute,
}

const MySentencesIdRouteWithChildren = MySentencesIdRoute._addFileChildren(
  MySentencesIdRouteChildren,
)

interface PracticeIdRouteChildren {
  PracticeIdEditRoute: typeof PracticeIdEditRoute
  PracticeIdIndexRoute: typeof PracticeIdIndexRoute
}

const PracticeIdRouteChildren: PracticeIdRouteChildren = {
  PracticeIdEditRoute: PracticeIdEditRoute,
  PracticeIdIndexRoute: PracticeIdIndexRoute,
}

const PracticeIdRouteWithChildren = PracticeIdRoute._addFileChildren(
  PracticeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnkiRoute: AnkiRoute,
  CaptureRoute: CaptureRoute,
  CultureRoute: CultureRoute,
  GrammarRoute: GrammarRoute,
  RenshuuRoute: RenshuuRoute,
  SentencesRoute: SentencesRoute,
  SettingsRoute: SettingsRoute,
  VocabRoute: VocabRoute,
  VocabularyRoute: VocabularyRoute,
  CapturesIdRoute: CapturesIdRoute,
  LessonsSlugRoute: LessonsSlugRoute,
  LessonsNewRoute: LessonsNewRoute,
  MySentencesIdRoute: MySentencesIdRouteWithChildren,
  MySentencesNewRoute: MySentencesNewRoute,
  PracticeIdRoute: PracticeIdRouteWithChildren,
  PracticeNewRoute: PracticeNewRoute,
  SourcesIdRoute: SourcesIdRoute,
  CapturesIndexRoute: CapturesIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  MySentencesIndexRoute: MySentencesIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
